java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    "recipes-sds-kv":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
