java:
  # Don't modify below here
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_SSL_MODE: require
  keyVaults:
    "recipes-cft-kv":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
