java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_SSL_MODE: require
  keyVaults:
    "recipes-sds-kv":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE-v14
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST-v14
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER-v14
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS-v14
          alias: POSTGRES_PASSWORD
