java:
  applicationPort: 4550
  readinessPath: '/health/readiness'
  # Don't modify below here
  image: 'hmctspublic.azurecr.io/recipes/backend:latest'
  environment:
    POSTGRES_SSL_MODE: require
  autoscaling:
    enabled: false
    enabledForDevMode: true
    maxReplicas: 5
    cpu:
      enabled: false
