java:
  applicationPort: 4550
  aadIdentityName: cnp
  readinessPath: '/health/readiness'
  # Don't modify below here
  image: 'hmctspublic.azurecr.io/recipes/backend:latest'
  environment:
    POSTGRES_SSL_MODE: require
  autoscaling:
    enabled: false
    enabledForDevMode: true
    maxReplicas: 5
    cpu:
      enabled: false
  keyVaults:
    "recipes-cft-kv":
      secrets:
        - name: recipe-backend-POSTGRES-DATABASE
          alias: POSTGRES_DATABASE
        - name: recipe-backend-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: recipe-backend-POSTGRES-USER
          alias: POSTGRES_USER
        - name: recipe-backend-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
